// Shared types for messages exchanged with the backend
// Ideally, this should be autogenerated...

export type ScriptStatus = 'on_script' | 'off_script' | 'idle';

export type ServerMessage =
  | { type: 'ready'; token_count: number }
  | { type: 'pointer'; index: number; confidence: number; tentative: boolean }
  | { type: 'transcript'; text: string; is_final: boolean }
  | { type: 'state'; status: ScriptStatus }
  | { type: 'error'; message: string; recoverable: boolean };
